### ISSUE TITLE
Lower minimum R version

### ISSUE THREAD

**Issue by mfansler** [spedygiorgio/markovchain#215]
Same issue as here: https://github.com/spedygiorgio/lifecontingencies/issues/35

On [the most recent build](https://github.com/conda-forge/r-markovchain-feedstock/pull/22) in this package's Conda Forge feedstock, patching to allow R >=4.1.0, shows that installation works for R v4.1 and v4.2, and all `testthat` tests pass. 

Consider only raising minimum R version when there is evidence of incompatibility.

**Comment by maikol-solis** [comment]
I have the same issue on a server with 4.2. I cannot install this package. 

Tracking down the repo history, I found that the problem is with this commit. 

https://github.com/spedygiorgio/markovchain/commit/2ce49a9062b7130bd9d5fcfdc7f95ef7b6f9d1f4#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231cR26

**Comment by maikol-solis** [comment]
I could install it with this command 

```
remotes::install_github(repo = "spedygiorgio/markovchain", ref = "db9f30d9387790cd4911619769de4395c09fdbd6")
```

**Comment by spedygiorgio** [comment]
Hello @maikol-solis  and @mfansler I have just pushed a new commit and released a new version of the package that lowers the requirements of the package. Please let me know if this resolves the issue you raised

**Comment by mfansler** [comment]
I'm fine with this. I expect we'll phase out R v4.1 package builds on Conda Forge soon-ish, so minimum v4.2 is okay.
