### ISSUE TITLE
RcppParallel in rmarkovchain for markovchainList object

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#66]
Good to use the RcppPackage for parallelizing calculations in Rcpp. Add a , num.cores=NULL parameters

**Comment by spedygiorgio** [comment]
need omogeneization of names

**Comment by cryptomanic** [comment]
Added parallel parameter to `rmarkovchain`. Rcpp Parallel implementation is integrated with `rmarkovchain`. In order to use RcppParallel implementation set `useRcpp = TRUE` , `parallel = TRUE`.

RcppParallel implementation is faster than Rcpp implementation.
```
> microbenchmark(rmarkovchain(10000, mclist, "matrix", include.t0 = TRUE, useRCpp = TRUE, parallel = TRUE), 
+                rmarkovchain(10000, mclist, "matrix", include.t0 = TRUE, useRCpp = TRUE, parallel = FALSE))
Unit: milliseconds
                                                                                            expr      min       lq     mean   median
  rmarkovchain(10000, mclist, "matrix", include.t0 = TRUE, useRCpp = TRUE,      parallel = TRUE) 34.35700 36.48785 38.14804 37.27256
 rmarkovchain(10000, mclist, "matrix", include.t0 = TRUE, useRCpp = TRUE,      parallel = FALSE) 77.04379 80.39403 85.39222 82.37782
```

`rmarkovchain` is up and ready for 3 cases.

```
useRcpp = TRUE, parallel = TRUE
useRcpp = TRUE, parallel = FALSE
useRcpp = FALSE, parallel = FALSE
```

Please have a look and let me know the issues.

**Comment by spedygiorgio** [comment]
Great job, what is needed is to:
1. kill markovchainSequenceParallel not to be exposed
2. add few lines in the main vignette

**Comment by cryptomanic** [comment]
done
