### ISSUE TITLE
optimize verification of markovchainList object

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#68]
the checkValidity internal method now verifies if the states(markovchain[t+i]) contains states(markovchain[t]). But a better approach is that states(markovchain[t+1]) contains the set of states reachable when the chain is in state[t]. That is it should verify that names(markovchain[t+1]) contains all the states j for which p_ij(t)>0

**Comment by cryptomanic** [comment]
With respect to previous version of `checkSequence` method below  sequence is invalid since {a, b, c} is not a subset of {a, b, d}. But we know that the sequence is valid. We cannot reach the state c after first transition. So we need to check that {a, b} is  a subset of {a, b, d} or not. In this case it is true. So sequence is valid.
```
> mcA
Unnamed Markov chain 
 A  3 - dimensional discrete Markov Chain with following states: 
 a, b, c 
 The transition matrix   (by rows)  is defined as follows: 
    a   b c
a 0.5 0.5 0
b 0.5 0.5 0
c 0.5 0.5 0

> mcB
Unnamed Markov chain 
 A  3 - dimensional discrete Markov Chain with following states: 
 a, b, d 
 The transition matrix   (by rows)  is defined as follows: 
    a   b d
a 0.5 0.5 0
b 0.5 0.5 0
d 0.5 0.5 0
```

Result of new approach
```
> mclist <- list(mcA, mcB) 
> .checkSequence(mclist)
[1] TRUE
```
